<?php

namespace Smirik\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Smirik\QuizBundle\Entity\Question;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
  
  /**
   * Get total number of questions for quiz
   * @param Smirik\QuizBundle\Entity\Quiz $quiz
   * @return integer
   */
  public function getNumberOfQuestionsForQuiz($quiz)
  {
    $query = $this->getEntityManager()->createQuery('SELECT COUNT(q.id) FROM SmirikQuizBundle:Question q');
    $count = $query->getSingleScalarResult();
    return $count;
  }
  
}